#version 430

// process cubes in chunks of 128
layout(local_size_x = 256, local_size_y = 1, local_size_z = 1) in;

layout(std430, binding = 0) buffer position_buffer {
    vec4 positions[];
};

uniform float dt;


void main() {
   
    uint index = gl_GlobalInvocationID.x;

    // Get the input data
    vec4 input = positions[index];

    // Modify the input with a sinusoidal delta
    input.x += 0.01;
    input.y += 0.01;

    positions[index] = input;
}